# Generated by Django 3.2.5 on 2023-04-27 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20230427_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContestParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('positive_feedback', models.TextField()),
                ('negative_feedback', models.TextField()),
                ('common_feedback', models.TextField()),
                ('mark_feedback', models.IntegerField()),
                ('contest_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.contest')),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='participants',
            field=models.ManyToManyField(through='api.ContestParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
